### ISSUE TITLE
【严重】产品管理界面无数据，影响研发模块流程无法走通

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#1]
@wanwb 
[概要]：【研发管理】产品管理界面无数据，影响研发模块流程无法走通
[详细步骤]：
1.用户门户，注册申请租户xie0304，
2.管理门户下审批通过后
3.用户门户，xie0304租户管理登录后，创建租户下的用户A，A用户分配权限产品管理员权限
4.用户A登录后，在研发管理->创建产品，创建产品名称为xie_product01后，但是产品管理界面不显示刚创建的数据。影响研发模块流程无法走通。
[实际结果]：
产品管理无数据，影响研发模块流程无法走通
[预期结果]:
产品管理界面数据显示正常
[重现率]:100%

**Comment by guohong1** [comment]
这个问题，你在创建产品的时候指定了产品管理员，以产品管理员账号登录就可以看到相应的产品

**Comment by xiexm** [comment]
通过通过，此问题由于切换用户登录后，界面列表数据显示当前登录用户的上一个用户的数据而导致的。
