### ISSUE TITLE
[一般][研发管理]创建产品后，且产品被工程引用后，依然可以修改产品信息

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#10]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[一般][研发管理]创建产品后，且产品被工程引用后，依然可以修改产品信息
[详细步骤]：
1.用户门户登录
2.研发管理->创建产品->添加界面，添加一条产品数，且产品代码为:xie_product
3.研发管理->产品管理->申请开通版本库功能
4.管理门户->租户管理->版本库开通，选择刚添加的产品xie_product，开通产品版本库
5.研发管理->创建工程，创建工程时应用产品：xie_product，且添加工程成功
6.研发管理->创建产品，选择产品xie_product，点击超链接修改产品信息，可以修改成功
[实际结果]：
产品被工程引用后，可以修改产品
[预期结果]:
产品被工程引用后，不建议修改产品信息。
[重现率]:100%

**Comment by guohong1** [comment]
经文斌确认， 产品被工程引用后，可以修改产品

**Comment by xiexm** [comment]
验证通过。
