### ISSUE TITLE
[一般]创建工程编辑界面选择工程管理员，不能自动区别原先已选用户。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#11]
[用户门户]研发管理-创建工程界面-超链接进入编辑界面，选择工程管理员用户时，界面不能自动区别原先已选的用户。建议原先已选的用户为打勾状态区别。
环境win7
浏览器：火狐
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[用户门户]创建工程编辑界面选择工程管理员，不能自动区别原先已选用户。
[详细步骤]：
1.研发管理-创建工程界面，超链接进入编辑界面，选择工程管理员用户时，界面不能自动区别原先已选用户，建议原先已选的用户为打勾状态区别。
[实际结果]：
界面不能自动区别原先已选用户
[预期结果]:
可以自动区别原先已选用户
[重现率]:100%

**Comment by zhangft** [comment]
一个用户可以管理多个工程的

**Comment by xiexm** [comment]
构建工程界面，超链接进入编辑界面，选择工程管理员用户时，界面不能自动区别原先已选用户。

**Comment by haoyh1** [comment]
@xiexm 这无关紧要 ，不影响业务逻辑和功能，经讨论不修改。

**Comment by xiexm** [comment]
此问题，咱不修改，正常关闭
