### ISSUE TITLE
[一般]镜像定义界面，在产品和工程下拉列表框输入查询内容后，内容显示不全，建议调整间距

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#12]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[一般]镜像定义界面，在产品和工程下拉列表框输入查询内容后，内容显示不全，建议调整间距
[详细步骤]：
1.镜像定义界面，在产品和工程下拉列表框输入查询内容后，内容显示不全，建议调整间距
[实际结果]：
搜索条件，按产品和工程下拉列表框内容显示不全。
[预期结果]:
搜索条件后，产品和工程下拉列表框内容显示完整。
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm   该问题已解决。（改了一下拉框的宽度，最多显示10个汉字，多余10个也会显示不全）

**Comment by xiexm** [comment]
验证通过。
