### ISSUE TITLE
[一般]镜像管理，反复点击查询按钮后，出现同一条数据重复多次加载问题

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#15]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[一般]镜像管理，反复点击查询按钮后，出现同一条数据重复多次加载问题
[详细步骤]：
1.研发管理-镜像管理，反复点击查询按钮后，查询同一条数据重新加载多次的问题
[实际结果]：
数据重复加载问题
[预期结果]:
数据显示正确。
[重现率]:非100%

**Comment by renfeng3** [comment]
@xiexm 已修复 重新构建paas-wdev工程代码后生效

**Comment by xiexm** [comment]
验证通过。
