### ISSUE TITLE
【一般】研发管理-构建管理，添加界面，点提交按钮，提示call remote service 'PcBuildSvc.saveOrUpdateDef()' error!  is exists build-name 'build01...

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#16]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[用户门户]研发管理-构建管理，添加界面，输入已存在的构建名时，点击提交按钮，提示：call remote service 'PcBuildSvc.saveOrUpdateDef()' error!  is exists build-name 'build01'! （其他界面也有类似问题，建议统一修改提示信息）
[详细步骤]：
1.研发管理-构建管理，添加界面，输入已存在的构建名时 ，点击提交按钮，提示：call remote service 'PcBuildSvc.saveOrUpdateDef()' error!  is exists build-name 'build01'! 
2.建议改成中文提示信息。
[实际结果]：
提示信息有误
[预期结果]:
建议统一修改提示信息，如：您输入的构建名XX已经存在。
[重现率]:100%

**Comment by renfeng3** [comment]
@xiexm 已修复

**Comment by xiexm** [comment]
问题重复，暂时关闭。
