### ISSUE TITLE
[一般]研发管理-构建管理，添加界面，界面排版错乱。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#17]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[用户门户]研发管理-构建管理，添加界面，界面排版错乱。
[详细步骤]：
1.用户界面登录，
2.研发管理-构建管理，添加界面，界面排版显示错乱。
[实际结果]：
界面排版错乱
[预期结果]:
界面显示正常
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm 在我这块显示是好的，电脑浏览器分辨率设为125%时就错乱了，这是样式没固定。

**Comment by guohong1** [comment]
已修改

**Comment by xiexm** [comment]
验证通过。

**Comment by xiexm** [comment]
验证通过，
