### ISSUE TITLE
[一般]研发管理-镜像定义界面，按工程查询时，下拉列表无数据

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#18]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[详细步骤]：
1.用户门户登录
2.研发管理-镜像定义界面， 按工程查询时，下拉列表框无数据，因查询条件产品和工程是依赖的关系，选择产品后，对应工程下拉列表才会有数据。
3.建议:修改工程查询按钮默认置灰或隐藏，当选择产品后，工程字段点亮或显示(注：构建管理/镜像管理/发布管理查询都有此问题)
[实际结果]：
研发管理-镜像定义界面，按工程查询时，下拉列表无数据，
[预期结果]:
方案一：工程查询字段默认隐藏，选择产品后，对应工程显示
方案二：工程查询默认置灰，选择产品后，工程字段点亮。
（注：构建管理/镜像管理/发布管理查询都有此问题)
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm    已改完

**Comment by xiexm** [comment]
问题未全部修复，镜像定义已ok，但是构建管理/镜像管理/发布管理存在以上问题，建议统一修改。

**Comment by haoyh1** [comment]
镜像定义,构建管理,镜像管理,发布管理,  四个页面已修改。  构建之后生效

**Comment by xiexm** [comment]
验证通过。
