### ISSUE TITLE
[一般]研发管理-创建产品，添加界面，选择产品管理员用户界面，用户信息数据显示错误

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#19]
[用户门户]研发管理-创建产品，添加界面，选择产品管理员用户界面，用户信息数据显示错误，预期结果：显示具有产品管理员权限的用户。
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：研发管理-创建产品，添加界面，选择产品管理员用户界面，用户信息数据显示错误
[详细步骤]：
[用户门户]研发管理-创建产品，添加界面，选择产品管理员用户界面，用户信息数据显示错误
[实际结果]：
显示不具有产品管理员权限的用户信息
[预期结果]:
预期结果：显示具有产品管理员权限的用户。
[重现率]:100%
[版本号]:

**Comment by renfeng3** [comment]
@xiexm 据讨论  暂不改

**Comment by xiexm** [comment]
此问题咱不修改，正常关闭。
