### ISSUE TITLE
[一般]研发管理-创建产品/创建工程/镜像定义界面，添加时，界面报错call remote service 'PcProductSvc.saveO....

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#21]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[一般]研发管理-创建产品/创建工程/镜像定义界面，添加时，界面报错call remote service 'PcProductSvc.saveO....
[详细步骤]：
[用户门户]研发管理-创建产品/创建工程/镜像定义，添加界面: 
 1.输入已经存在的产品代码后，                                                                                                   
 2.输入已经存在的工程代码，                                                                                                          
 3.输入已经存在的镜像名 ,
 4.点击提交按钮，报错call remote service 'PcProductSvc.saveOrUpdate()' error!  is exists code '01234567890123456'! ，建议修改此提示信息如：您输入的产品代码/工程代码/镜像名已经存在，请重新输入.
[实际结果]：
界面提交信息不友好
[预期结果]:
建议修改此提示信息如：您输入的产品代码/工程代码/镜像名已经存在，请重新输入.

**Comment by haoyh1** [comment]
@xiexm   这是哪个页面呀？是 创建产品  ，   创建工程  ，   镜像定义界面 这三个页面都有这个提示吗？

**Comment by haoyh1** [comment]
@xiexm   这个页面提示信息来源于后台抛出的异常，和万文斌沟通过了，这个抛异常的地不能去处理，处理了反而会影响保存修改的业务逻辑

**Comment by haoyh1** [comment]
@xiexm   这个提示来源于后台抛出的异常，和万文斌沟通过了

**Comment by haoyh1** [comment]
@xiexm  这个提示来源于后台抛的异常，和万文斌沟通过了

**Comment by haoyh1** [comment]
@xiexm  这个提示来源于后台抛的异常，一做处理反而会出错，要彻底修改 建议找万文斌。
