### ISSUE TITLE
[一般]研发管理-创建工程界面，修改工程状态为：停用时，工程管理界面，可以查看到此数据。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#22]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[建议]研发管理-创建工程界面，修改工程状态为：停用时，工程管理界面，可以查看到此数据。
[详细步骤]：
1.研发管理-创建工程界面，创建一条工程数据，如：xie_project01,修改此数据状态为：停用
2.工程管理员登录，界面显示此已停用的数据
3.因镜像定义的时候，已停用的工程是不能被定义引用的，因此建议工程管理界面，不显示已停用的工程信息。
[实际结果]：
已停用的工程数据，显示在研发管理-工程管理列表界面。
[预期结果]:
已停用的工程数据，不显示在研发管理-工程管理列表界面。
[重现率]:100%

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：工程管理界面，不显示已停用的工程信息。
2）、代码分支说明：https://github.com/AIPaaS/PaaS-FE-DEV.git   develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无
@xiexm

**Comment by xiexm** [comment]
验证通过。
