### ISSUE TITLE
【验证】构建管理，添加界面，点击构建按钮，提示构建成功，但实际数据无法插入镜像表pc_image中

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#23]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
研发管理-构建管理，添加界面，点击构建按钮后，提示构建成功后，数据无法插入镜像表pc_image中（此问题导致镜像构建流程无法走通）
[详细步骤]：
1.研发管理-构建管理，添加界面，点击构建按钮后，提示构建成功，但实际数据无法插入镜像表pc_image中，
[实际结果]：
构建失败
[预期结果]:
构建成功，镜像表pc_image中有数据。
[重现率]:100%

**Comment by zhaolijing1990** [comment]
@xiexm 问题已找到原因。
是因为：测试环境中的数据问题。res数据库中找不到 快照版本的 镜像仓库的记录。
请修订数据库中的数据，重新测试。

**Comment by xiexm** [comment]
验证通过。
