### ISSUE TITLE
[一般]构建管理界面，点击历史任务按钮后，弹出提示：查询失败。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#24]
[用户门户]研发管理-构建管理界面，点击历史任务按钮，界面弹出提示：查询失败的信息。
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
研发管理-构建管理界面，点击历史任务按钮后，过一会弹出提示：查询失败的信息
[详细步骤]：
研发管理-构建管理界面，点击历史任务按钮后，过一会弹出提示：查询失败的信息
[实际结果]：
弹出提示信息有误
[预期结果]:
弹出信息正常
[重现率]:100%

**Comment by oriiro** [comment]
已改完。验证后 请关闭。

**Comment by xiexm** [comment]
验证通过。
