### ISSUE TITLE
[一般]研发管理-构建管理界面，先点击构建按钮，在构建过程中点击中断按钮无反应。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#26]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[一般]研发管理-构建管理界面，先点击构建按钮，在构建过程中点击中断按钮无反应。
[详细步骤]：
1.研发管理-构建管理界面，点击构建按钮，在构建过程中点击中断按钮无反应
[实际结果]：
构建过程中的点击中断按钮无响应
[预期结果]:
构建过程中点击中断按钮，可正常停止构建
[重现率]:100%

**Comment by haoyh1** [comment]
已修改，原因是掉构建时已经出错了没做处理，结果页面显示构建中，显示了中止按钮。

**Comment by haoyh1** [comment]
@xiexm 已修改，原因是掉构建时已经出错了没做处理，结果页面显示构建中，显示了中止按钮。

**Comment by xiexm** [comment]
验证通过。
