### ISSUE TITLE
[一般]创建产品和工程时，产品代码和工程没有校验大写。(预期结果：不能输入大写)

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#29]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[一般]创建产品和工程时，产品代码和工程没有校验大写。(预期结果：不能输入大写)
[详细步骤]：
创建产品和工程时，产品代码和工程代码没有校验大写，
[实际结果]：
没有校验大写
[预期结果]:
因api接口，不支持输入大写，建议前台界面做校验
[重现率]:100%
[版本号]:

**Comment by zhaolijing1990** [comment]
这个问题，昨天下午 任峰已经解决完毕

**Comment by renfeng3** [comment]
@xiexm 已修复

**Comment by xiexm** [comment]
验证通过。
