### ISSUE TITLE
[一般]A租户登录用户门户，在研发管理-创建产品列表，可以看到其他租户创建的产品信息。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#3]
@wanwb 
[概要]：
[一般]A租户登录用户门户，在研发管理-创建产品列表，可以看到其他租户创建的产品信息。
[详细步骤]：
1.用户门户，租户管理员A登录后，创建产品，如：xie_prouct01
2.再用租户管理员B登录后，在研发管理-创建产品列表可以看到租户A创建的产品数据。
[实际结果]：
租户管理员A登录后，在研发管理-创建产品列表，可以看到其他租户创建的产品数据。
[预期结果]:
租户A不能看到其他租户的产品信息，只能看A自己创建的产品或A租户下的用户的创建的产品。
[重现率]:100%

**Comment by guohong1** [comment]
已修改

**Comment by guohong1** [comment]
在我本地查询是正常的，可能测试环境的代码有问题，再测一次吧

**Comment by xiexm** [comment]
验证通过。
