### ISSUE TITLE
[一般]构建管理界面，点击删除按钮，无反应

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#30]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
构建管理界面，点击删除按钮，无反应
[详细步骤]：
1.构建管理界面，点删除按钮，无反应
[实际结果]：
删除按钮无反应
[预期结果]:
正常删除
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm   这是昨天5点构建之前的问题，这个bug昨天已修复。

**Comment by xiexm** [comment]
验证通过。
