### ISSUE TITLE
[一般]构建管理界面，点击构建名超链接后，进入修改界面，勾选[是否外部工程]后，点击提交按钮，提交失败

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#31]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[用户门户]构建管理界面，点击构建名超链接后，进入修改界面，勾选[是否外部工程]后，点击提交按钮，提交失败。[预期结果：建议是否外部工程置灰，不允许修改]
[详细步骤]：
1.构建管理界面，点击构建名超链接后，进入修改界面，勾选是否【是否外部工程】后，点击提交按钮，提交失败，
[实际结果]：
提示失败
[预期结果]:
修改界面，不允许修改时外部工程
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm  已修改

**Comment by xiexm** [comment]
验证通过。
