### ISSUE TITLE
[一般]构建管理界面，定义外部工程时，点击提交按钮，提示:请选择一项，但实际字段已经录入值。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#32]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
用户门户]构建管理界面，定义外部工程时，点击提交按钮，提示：请选择一项，但实际字段已经输入值，则外部工程定义失败
[详细步骤]：
1.构建管理界面，定义外部工程时，点击提交按钮，提交：请选择一项，但实际字段已经录值值，则外部工程定义失败
[实际结果]：
外部工程构建定义时失败
[预期结果]:
功能正常
[重现率]:100%
[版本号]:

**Comment by haoyh1** [comment]
@xiexm  已修改

**Comment by xiexm** [comment]
验证通过
