### ISSUE TITLE
[一般]  研发管理->产品管理列表界面，操作[文档库权限管理]按钮不起作用。 

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#33]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[一般]  研发管理->产品管理列表界面，操作[文档库权限管理]按钮不起作用。 
[详细步骤]：
[一般]  研发管理->产品管理列表界面，操作[文档库权限管理]按钮不起作用。 
[实际结果]：
功能未实现
[预期结果]:
现阶段若不做，建议隐藏此按钮。
[重现率]:100%

**Comment by haoyh1** [comment]
@xiexm   已修改，   （构建后生效）

**Comment by xiexm** [comment]
此问题不做开发，正常关闭
