### ISSUE TITLE
[一般]研发管理-发布管理，选择资源数据中心显示不对，导致无法发布镜像。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#34]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[一般]研发管理-发布管理，选择资源数据中心显示不对，导致无法发布镜像。
[详细步骤]：
研发管理-发布管理，选择资源数据中心数据显示不对，导致无法发布镜像。
[实际结果]：
数据显示不对，无法发布镜像
[预期结果]:
数据显示正确
[重现率]:100%

**Comment by renfeng3** [comment]
@xiexm 已修复 重新构建后生效

**Comment by xiexm** [comment]
验证通过。
