### ISSUE TITLE
[一般]创建产品-添加界面，选择产品管理时，在弹出的选择用户界面全选按钮显示问题

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#4]
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[一般]创建产品-添加界面，选择产品管理时，在弹出的选择用户界面全选按钮显示问题
[详细步骤]：
1.用户登录登录 xie0304/admin/123456
1.【用户门户】研发管理->创建产品->添加产品->选择产品管理员时，在弹出的选择用户界面              2.先点击全选按钮，数据全部选中，再把其中一条数据的打勾取消后，则全选按钮依然是打勾状态 
[实际结果]：
全选按钮显示问题
[预期结果]:
2.预期结果：数据未全部选中时，全选按钮不打勾；
[重现率]:100%
@wanwb

**Comment by guohong1** [comment]
已修改

**Comment by xiexm** [comment]
验证失败，1.【用户门户】研发管理->创建产品->添加产品->选择产品管理员时，在弹出的选择用户界面 2.逐步一一勾选数据，使得所有的数据为选中状态时，则全选按钮此时没有打勾（预期结果：全选按钮打勾）

**Comment by xiexm** [comment]
验证通过。
