### ISSUE TITLE
[一般]发布管理界面，不显示tag号信息

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#42]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：[一般]发布管理界面，不显示tag号信息
[详细步骤]：
发布管理界面，不显示tag号信息
[实际结果]：
tag不显示
[预期结果]:
正常显示
[重现率]:100%

**Comment by renfeng3** [comment]
@xiexm 以修复

**Comment by xiexm** [comment]
验证通过，
