### ISSUE TITLE
[一般]镜像定义->添加界面，勾选是否外部镜像功能后，没有选择路径地址，导致无法上传外部镜像。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#5]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：镜像定义->添加界面，勾选是否外部镜像后，没有选择路径地址
[详细步骤]：
1.用户门户登录  xie0304/admin/123456
2.研发管理->镜像定义->添加界面，勾选【是否外部镜像】功能后，没有选择路径地址
[实际结果]：
外部镜像，无法上传外部镜像
[预期结果]:
外部镜像功能正常，可以上传外部镜像文件。
@wanwb 
[重现率]:100%

**Comment by guohong1** [comment]
不需要选择路径地址

**Comment by xiexm** [comment]
开发意见：不需要选择路径地址，正常关闭。
