### ISSUE TITLE
[一般]构建管理-添加时，勾选[是否自动推送到开发环境]按钮后，资源中心无数据。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#6]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：构建管理-添加时，勾选[是否自动推送到开发环境]按钮后，资源中心无数据。
[详细步骤]：
1.用户界面登录 xie0304/xie01/123456
2.研发管理->构建管理->添加界面，勾选【是否自动推送到开发环境】按钮后，资源中心无数据，注：此问题由于电脑分辩率低
注：资源中心中的数据来源于管理门户-》资源管理-》资源中心，且资源类型为开发，镜像为非快照。
[实际结果]：
字段资源中心取不到值
[预期结果]:
资源中心数据显示正常
[重现率]:100%

**Comment by guohong1** [comment]
是否推送到开发环境和资源中心都在页面中去掉了

**Comment by xiexm** [comment]
此功能去掉，正常关闭。
