### ISSUE TITLE
[一般]版本库开通界面，字段版本库URL输入特殊字符可以保存成功。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#7]
环境win7
浏览器：火狐
测试环境：
管理门户：http://10.1.245.248:16002/paas-console
[概要]：管理门户-租户管理->版本库开通，输入字段【版本库URL】没做校验，输入特殊字符可以保存成功。
[详细步骤]：
1.管理门户-租户管理-版本库开通，输入字段【版本库URL】没做校验，输入特殊字符可以保存成功
[实际结果]：
版本库URL可以输入特殊字符。
[预期结果]:
不能输入特殊字符，应正确验证URL合法性正则表达式。
[重现率]:100%

**Comment by guohong1** [comment]
版本库URL控制了长度不能超过300个字符，不需要校验特殊字符

**Comment by xiexm** [comment]
验证失败，
问题1：输入汉字时可以保存成功
问题2：输入等于300个汉字时，点击打勾按钮，提示call remote service 'VcMntRepositoryApplySvc.openUpGit()' error! Data truncation: Data too long for column 'RESP_CODE_URL' at row 1

**Comment by guohong1** [comment]
已修改，现在限制的长度是不能超过200

**Comment by xiexm** [comment]
验证通过。
