### ISSUE TITLE
[一般]创建产品/产品管理界面，在查询字段文本框中按enter后，弹出下拉列表框且其中数据显示错误。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#8]
环境win7
浏览器：火狐、Chrome
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[详细步骤]：
a.用户门户,fixfox下，研发管理->创建产品/产品管理/创建工程/工程管理界面，
b.在查询字段文本框中按enter 键后，弹出下拉列表框且其中的数据显示错误【预期结果：文本框输入不应该弹出下拉列表】
[实际结果]：
查询字段文本框中按enter按后，弹出下拉列表框和数据显示错误
[预期结果]:
文本框输入不应该弹出下拉列表框。
[重现率]:100%
[版本号]:

**Comment by guohong1** [comment]
那个应该是浏览器的浏览记录，是浏览器的问题

**Comment by xiexm** [comment]
验证通过。
