### ISSUE TITLE
[建议]产品管理查询界面，建议按【文档库类型】进行查询检索。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-DEV#9]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：研发管理-产品管理查询界面，不能按文档库类型查询，建议实现按【文档库类型】查询功能
[详细步骤]：
1.用户门户，研发管理-产品管理列表界面，查询条件中不能按文档库类型查询，建议实现【文档库类型】查询功能
[实际结果]：
不能按文档库类型查询
[预期结果]:
可以按文档库类型查询
[重现率]:100%

**Comment by guohong1** [comment]
已添加

**Comment by xiexm** [comment]
验证通过。
